// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/21/2026, 11:02:57 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/bibirinbuluaremieye/Documents/portfolio-1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bibirinbuluaremieye/Documents/portfolio-1/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bibirinbuluaremieye/Documents/portfolio-1/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bibirinbuluaremieye/Documents/portfolio-1/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bibirinbuluaremieye/Documents/portfolio-1/plugins/**/*.{js,ts,mjs}","/Users/bibirinbuluaremieye/Documents/portfolio-1/composables/**/*.{js,ts,mjs}","/Users/bibirinbuluaremieye/Documents/portfolio-1/utils/**/*.{js,ts,mjs}","/Users/bibirinbuluaremieye/Documents/portfolio-1/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/bibirinbuluaremieye/Documents/portfolio-1/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/bibirinbuluaremieye/Documents/portfolio-1/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/bibirinbuluaremieye/Documents/portfolio-1/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;